import test from 'node:test';
import assert from 'node:assert/strict';
import { createGame, reduce } from '../engine.ts';
import type { EngineContext } from '../types.ts';
import { addFearToHand, setupLeader, runLeaderRoundStart, runLeaderRoundEnd } from './index.ts';
import { baronessPlaySpecialDelivery, captainCallSpecialist, explorerSpendSnack, falconerAdvanceEagle, falconerReturnEagle, mysticPerformRitual, professorBuyArchiveArtifact } from './actions.ts';

const leaderNames=['Funding','Piloting','Transmission','Hidden Fear','Falconry','Animal Bond','Tracking','Connections','Research Notes','Resourcefulness','Special Delivery','Preservation','Arnakology','Linguistics','Hike','Cartography','Scouting','Divine Guidance','Meditation','Worldly Goods','Blindsight'];
const cards:EngineContext['cards']={fear1:{id:'fear1',name:'Fear',type:'Fear',expansion:'Base Game'},fear2:{id:'fear2',name:'Fear',type:'Fear',expansion:'Base Game'},a1:{id:'a1',name:'Archive A',type:'Artifact',expansion:'Base Game',cost:3},a2:{id:'a2',name:'Archive B',type:'Artifact',expansion:'Base Game',cost:2},a3:{id:'a3',name:'Archive C',type:'Artifact',expansion:'Base Game',cost:1},a4:{id:'a4',name:'Archive D',type:'Artifact',expansion:'Base Game',cost:3},a5:{id:'a5',name:'Archive E',type:'Artifact',expansion:'Base Game',cost:3},a6:{id:'a6',name:'Archive F',type:'Artifact',expansion:'Base Game',cost:3},item:{id:'item',name:'Test Item',type:'Item',expansion:'Base Game',cost:1}};for(const name of leaderNames)cards[`leader:${name}`]={id:`leader:${name}`,name,type:'Starter',expansion:'Expedition Leaders'};const context:EngineContext={cards};
function baseState(){const s=createGame(['p1']);s.phase='playing';s.setupSeed='test';s.players.p1.hand=['fear1'];s.players.p1.deck=['fear2'];s.market.artifactDeck=['a1','a2','a3','a4','a5','a6'];return s;}
test('Captain setup has three archaeologists and specialist is once per round',()=>{let s=baseState();setupLeader(s,'p1','captain',context,'seed');assert.equal(s.players.p1.workers,3);s.assistants.stacks=[['assistant-a']];s=captainCallSpecialist(s,'p1',0);assert.equal(s.players.p1.availableWorkers,2);assert.throws(()=>captainCallSpecialist(s,'p1',0),/already been used/);runLeaderRoundEnd(s,'p1',context);assert.equal(s.players.p1.leader!.data.specialistUsedThisRound,false);});
test('Falconer eagle advances and returns for a reached site reward',()=>{let s=baseState();setupLeader(s,'p1','falconer',context,'seed');runLeaderRoundStart(s,'p1',context);assert.equal(s.players.p1.leader!.data.eaglePosition,1);s=falconerAdvanceEagle(s,'p1',10);s=falconerReturnEagle(s,'p1',3);assert.equal(s.players.p1.leader!.data.eaglePosition,0);assert.deepEqual(s.pendingRewards[0].payload,{rewardPosition:3,mainAction:true});});
test('Falconer first two eagle returns resolve coin and tablet plus temporary plane',()=>{let s=baseState();setupLeader(s,'p1','falconer',context,'seed');s=falconerAdvanceEagle(s,'p1',1);s=falconerReturnEagle(s,'p1',1);assert.equal(s.players.p1.resources.coin,1);assert.equal(s.pendingRewards.length,0);s=falconerAdvanceEagle(s,'p1',2);s=falconerReturnEagle(s,'p1',2);assert.equal(s.players.p1.resources.tablet,1);assert.equal(s.actionWindow?.temporaryTravel.plane,1);assert.equal(s.pendingRewards.length,0);});
test('Baroness retrieves Special Delivery and must explicitly play it before delivering an Item to hand',()=>{let s=baseState();setupLeader(s,'p1','baroness',context,'seed');const delivery=s.players.p1.hand[0];s.players.p1.hand.splice(0,1);s.players.p1.playedCards.push(delivery);runLeaderRoundEnd(s,'p1',context);assert.ok(s.players.p1.hand.includes(delivery));s=baronessPlaySpecialDelivery(s,'p1');assert.ok(!s.players.p1.hand.includes(delivery));assert.equal(s.players.p1.leader!.data.specialDeliveryArmed,true);s.market.items=['item'];s.players.p1.resources.coin=1;s=reduce(s,{type:'BUY_CARD',playerId:'p1',cardId:'item'},context);assert.ok(s.players.p1.hand.includes('item'));assert.ok(!s.players.p1.deck.includes('item'));assert.equal(s.players.p1.leader!.data.specialDeliveryArmed,false);});
test('Baroness recovers Special Delivery even if it was exiled',()=>{let s=baseState();setupLeader(s,'p1','baroness',context,'seed');const delivery=s.players.p1.leader!.data.specialDeliveryCardId as string;s.players.p1.hand=s.players.p1.hand.filter(id=>id!==delivery);s.market.exiled.push(delivery);runLeaderRoundEnd(s,'p1',context);assert.ok(s.players.p1.hand.includes(delivery));assert.ok(!s.market.exiled.includes(delivery));});
test('Baroness without playing Special Delivery buys Item to deck normally',()=>{let s=baseState();setupLeader(s,'p1','baroness',context,'seed');s.market.items=['item'];s.players.p1.resources.coin=1;s=reduce(s,{type:'BUY_CARD',playerId:'p1',cardId:'item'},context);assert.ok(s.players.p1.deck.includes('item'));assert.ok(!s.players.p1.hand.includes('item'));});
test('Baroness round II income is granted once',()=>{const s=baseState();setupLeader(s,'p1','baroness',context,'seed');s.round=2;runLeaderRoundStart(s,'p1',context);assert.equal(s.players.p1.resources.coin,1);runLeaderRoundStart(s,'p1',context);assert.equal(s.players.p1.resources.coin,1);});
test('Professor creates archive and receives suitcase bonuses',()=>{let s=baseState();setupLeader(s,'p1','professor',context,'seed');assert.deepEqual(s.players.p1.leader!.data.archive,['a1','a2','a3']);s.round=2;runLeaderRoundStart(s,'p1',context);assert.equal((s.players.p1.leader!.data.suitcase as any).compass,1);s.players.p1.resources.compass=2;s=professorBuyArchiveArtifact(s,'p1','a1',context,1);assert.equal(s.players.p1.resources.compass,0);});
test('Explorer has one archaeologist and snack rules',()=>{let s=baseState();setupLeader(s,'p1','explorer',context,'seed');assert.equal(s.players.p1.workers,1);s=explorerSpendSnack(s,'p1','free','site-a');assert.throws(()=>explorerSpendSnack(s,'p1','free','site-b'),/already been used/);s.round=3;s.players.p1.resources.compass=1;s=explorerSpendSnack(s,'p1','compass','site-b');assert.equal(s.players.p1.resources.compass,0);});
test('Mystic adds Fear and supports all ritual tiers',()=>{let s=baseState();setupLeader(s,'p1','mystic',context,'seed');assert.ok(addFearToHand(s,'p1',context));s.players.p1.leader!.data.ritualPile=['fear1','fear1'];s=mysticPerformRitual(s,'p1',2);assert.equal(s.players.p1.resources.coin,1);s.players.p1.leader!.data.ritualPile=['fear1','fear1','fear1'];s=mysticPerformRitual(s,'p1',3);assert.equal(s.pendingRewards.at(-1)?.code,'leader:MYSTIC_BUY_ARTIFACT_DISCOUNT');s.players.p1.leader!.data.ritualPile=['fear1','fear1','fear1','fear1'];s=mysticPerformRitual(s,'p1',4);assert.equal(s.pendingRewards.at(-1)?.code,'leader:MYSTIC_OVERCOME_GUARDIAN_FREE');});
